import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: '#00796B',
  },
  grid: {height: '100%', width: '100%'},
  topBar: {flex: 0.5, backgroundColor: '#00796B'},
  bottomBar: {
    flex: 5,
    backgroundColor: '#00796B',
    flexDirection: 'column',
  },
  mainCol1: {
    flex: 1.5,
    backgroundColor: '#00796B',
    flexDirection: 'row',
  },
  col1: {
    flex: 1.5,
    backgroundColor: '#212121',
    alignContent: 'center',
    justifyContent: 'center',
    margin: 1,
  },
  face: {
    flex: 1,
    backgroundColor: '#00796B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  back: {
    flex: 1,
    backgroundColor: '#00796B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scoreView: {flex: 1, backgroundColor: 'transparent'},
  winView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnsView: {
    flex: 1,
    // backgroundColor: 'yellow',
    flexDirection: 'row',
  },
  btnReset: {
    flex: 1,
    backgroundColor: '#00796B',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowOpacity: 2,
    elevation: 8,
    shadowRadius: 5,
  },
  btnScoreCard: {
    flex: 1,
    backgroundColor: '#00796B',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowOpacity: 2,
    elevation: 8,
    shadowRadius: 5,
  },
  hits: {fontSize: 30, color: 'white'},
  hitsCount: {fontSize: 30, fontWeight: 'bold', color: 'white'},
  jsckImage: {width: '100%', height: '100%'},
  scoreCardTxt: {
    marginTop: 30,
    fontSize: 30,
    fontWeight: 'bold',
    color: '#FFC107',
    alignSelf: 'center',
  },
  btnClose: {
    width: '100%',
    backgroundColor: '#FFC107',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
  },
  txtClose: {
    color: '#212121',
    fontSize: 25,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  cardNumber: {
    fontSize: 60,
    fontWeight: 'bold',
    color: 'white',
  },
  txtReset: {
    fontSize: 15,
    color: 'white',
    fontWeight: 'bold',
  },
  txtScoreCard: {fontSize: 15, color: 'white', fontWeight: 'bold'},
  item: {
    backgroundColor: '#B2DFDB',
    padding: 5,
    marginVertical: 5,
    marginHorizontal: 10,
    flexDirection: 'row',
  },
  txtName: {
    flex: 5,
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 15,
    color: '#212121',
  },
  txtScore: {
    flex: 1,
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
  },
  flatList: {marginTop: 10},
});
